services:
#Services
 openldap:
  build:
    context: build
    args:
     ENVPATH: openldap.env
  extra_hosts:
  - "bastionado.isc:127.0.0.1"
  hostname: openldap
  ports:
  - "10000:10000"
  networks:
   ldap:
    ipv4_address: 192.168.99.100
  volumes:
   - ldapdata:/var/lib/ldap
 cliente:
  build:
    context: build
    args:
     ENVPATH: cliente.env
  extra_hosts:
  - "bastionado.isc:192.168.99.100"
  hostname: cliente
  environment:
   - DISPLAY=${DISPLAY}
  cap_add:
   - ALL
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
  networks:
   ldap:
networks:
  ldap:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: auth_ldap
    ipam:
     config:
       - subnet: 192.168.99.0/24
volumes:
 ldapdata:
