version: '3.5'
services:
#Services
 openldap:
  build:
    context: build
    args:
     ENVPATH: openldap.env
  hostname: openldap
  ports:
  - "10000:10000"
  networks:
   ldap:
    ipv4_address: 192.168.99.100
  volumes:
   - ldapdata:/var/lib/ldap
 cliente:
  build:
    context: build
    args:
     ENVPATH: cliente.env
  hostname: cliente
  networks:
   ldap:
networks:
  ldap:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: auth_ldap
    ipam:
     config:
       - subnet: 192.168.99.0/24
volumes:
 ldapdata:
