services:
#Services
 debian:
  build:
    context: build
    args:
     ENVPATH: debian.env
  hostname: debian
  networks:
   linwin:
    ipv4_address: 192.168.20.10
networks:
  linwin:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: ad_linwin
    ipam:
     config:
       - subnet: 192.168.20.0/24
