services:
#Services
 kdc:
  build:
    context: build
    args:
     ENVPATH: kdc.env
  hostname: kdc
  networks:
   kerberos:
    ipv4_address: 192.168.98.100
  volumes:
   - kerberosdata:/var/kerberos
   - kerbshare:/var/kerbshare
 cliente:
  build:
    context: build
    args:
     ENVPATH: cliente.env
  hostname: cliente
  networks:
   kerberos:
  volumes:
   - kerbshare:/var/kerbshare
 ssh:
  build:
    context: build
    args:
     ENVPATH: ssh.env
  hostname: ssh
  networks:
   kerberos:
    ipv4_address: 192.168.98.90
  volumes:
   - kerbshare:/var/kerbshare
networks:
  kerberos:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: auth_kerberos
    ipam:
     config:
       - subnet: 192.168.98.0/24
volumes:
 kerberosdata:
 kerbshare:
