machines=[
  {
    :hostname => "debiandesktop",
    :box => "debian_10.7.0_desktop",
    :ram => 2048,
    :cpu => 1,
    :bridgelan => "auth_radius"
  },
  {
    :hostname => "pfsenseradius",
    :box => "pfsense_2.5.1",
    :ram => 2048,
    :cpu => 1,
    :bridgelan => "auth_radius",
    :bridgewan => "auth_radiuswan"
  }
]

Vagrant.configure(2) do |config|
  machines.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.boot_timeout = 10
          if machine.key?(:bridgelan)
            node.vm.network "public_network", bridge: machine[:bridgelan]
          end
          if machine.key?(:bridgewan)
            node.vm.network "public_network", bridge: machine[:bridgewan]
          end
          node.vm.provider "virtualbox" do |vb|
              vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
              vb.name = machine[:hostname]
              vb.linked_clone = true
          end
        end
      end
    end
