services:
#Services
 kali:
  build:
    context: build
    args:
     ENVPATH: kali.env
  hostname: kali
 victima:
  image: debian:bullseye
  hostname: victima
  command: /bin/bash -c "while true;do sleep 5;done"
